In [6]:
import numpy as np

In [2]:
a = np.arange(29)

In [5]:
a[6]

np.int64(6)

In [8]:
b = np.arange(24).reshape((4,6))
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [9]:
b[0] # 二维数组获取某一行的数据

array([0, 1, 2, 3, 4, 5])

In [11]:
# 连续获取某几行的数据
b[0:3]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [13]:
# 获取不连续的某几行的数据
b[[0,1,3]]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [18, 19, 20, 21, 22, 23]])

In [14]:
# 通过负数来获取
d = np.arange(50).reshape((25,2))
d[[-1,-2]]

array([[48, 49],
       [46, 47]])

In [15]:
u = np.arange(24).reshape(6,4)
u

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [20]:
u[1,1] # 获取某行某列的数据

np.int64(5)

In [ ]:
'''
总结
1. 如果数组是⼀维的 那么索引和切⽚就是和python中的列表是⼀样的
2. 如果是多维的 那么在中扩中 给两个值 两个值是通过逗号分隔的 逗号前⾯是⾏ 后⾯是列 如果
中括号中只有⼀个值 那么就表示⾏
3. 如果是多维数组 那么⾏的部分和列的部分 都是遵循⼀维数组的⽅式 可以使⽤整形 切⽚ 还可以
使⽤中括号的形式 来代表不连续的
'''