In [1]:
import numpy as np

In [2]:
a = np.arange(16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [5]:
a2 = np.vsplit(a,2) # v水平切割 h垂直切割
a2

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [6]:
np.hsplit(a,[1,2]) # 代表在下标为1的地方切一刀，为2的地方也切一刀，因此分成了三部分

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [7]:
g = np.random.randint(1,10,size=(4,4))
g

array([[4, 4, 2, 2],
       [8, 8, 5, 4],
       [7, 9, 8, 1],
       [5, 7, 1, 5]], dtype=int32)

In [8]:
np.array_split(g,2,axis=0) # 水平切割

[array([[4, 4, 2, 2],
        [8, 8, 5, 4]], dtype=int32),
 array([[7, 9, 8, 1],
        [5, 7, 1, 5]], dtype=int32)]

In [9]:
np.array_split(g,2,axis=1) # 垂直切割

[array([[4, 4],
        [8, 8],
        [7, 9],
        [5, 7]], dtype=int32),
 array([[2, 2],
        [5, 4],
        [8, 1],
        [1, 5]], dtype=int32)]

In [ ]:
"""
1.np.vsplit(a,2(切割成几份) / [1,2](从1，2两个地方切割) ),按水平切割
2.np.hsplit(a,2/[1,2]),按垂直切割
3.np.array_split(a,axis=0/1),可手动设置切割方向,0代表水平切割，1代表垂直切割
"""