In [2]:
import numpy as np

In [4]:
# 一维数组切割
a = np.arange(10)
a[2:len(a):2] # 从2开始，到8结束，但不包含8，步长为2

array([2, 4, 6, 8])

In [6]:
# 多维数组切割
b = np.array([[1,2,3],[4,5,6],[7,8,9]]) # 三行三列
b[:2,1:] # 0,1 1,2 # 切片
print(b[0,1])
print(b[0,2])
print(b[1,1])
print(b[1,2])

2
3
5
6


In [7]:
c = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
c[::2,::2] # [1,2,3][7,8,9] 1,3,7,9

array([[1, 3],
       [7, 9]])

In [8]:
# 使用负数索引和步长
h = np.array([1,2,3,4,5,6,7,8,9,10])
h[-3:-1]

array([8, 9])