In [6]:
import numpy as np

In [7]:
a = np.array([1,2,3,8])

print(a)
print(a.ndim) # 获取维度

[1 2 3 8]
1


In [8]:
b = np.array([[1,2,3],[4,5,6]])
print(b)
print(b.ndim)

[[1 2 3]
 [4 5 6]]
2


In [9]:
c = np.array([[[8,9,7],[4,5,6]]])
print(c)
print(c.ndim)

[[[8 9 7]
  [4 5 6]]]
3


In [10]:
c.shape # 查询数组形状

(1, 2, 3)

In [11]:
print(c.size) # 总元素

6


In [12]:
print(c.itemsize) # 返回的是8，字节为8，每一个字节占8位

8


In [13]:
c.itemsize*c.size # 总字节
c.nbytes

48

In [14]:
a1 = np.array([1,2,3])
a1.shape # 返回的3，代表一维 有三个数据

(3,)

In [15]:
a2 = np.array([[1,2,3],[4,5,6]])
a2.shape

(2, 3)

In [16]:
a3 = np.array([[[1,2,3,4],[4,5,6,7],[7,8,9,5]],[[1,2,3,4,],[4,5,6,7],[7,8,9,10]]])
a3.shape # 2，3，4 返回的意思是 包含2个3*4的数组： 有两个大组，三个小组，每个小组里面有4个元素

(2, 3, 4)

In [17]:
a8 = np.arange(12)
a8.reshape((3,4)) # 修改形状
print(a8)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [30]:
a8.reshape((2,3,2)) # 两个大组，三个小组，每个小组里面有2个元素

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [43]:
u = np.array([[5,9,40,50],[6,8,9,10]])
print(u.ndim)
m = u.reshape(8,) # 将一个二维数组，变成一维数组
# 无论reshape怎么去修改，都不会影响原来的数组，而是将修改后的结果返回给一个新的数组。如果要修改，可以用resize替换
m.ndim

2


1

In [46]:
u.flatten()



array([ 5,  9, 40, 50,  6,  8,  9, 10])

In [ ]:
'''
总结
1. 数值⼀般达到3维就已经很复杂了,所以我们⼀般都会把3维以上的数组转换为2维数值进⾏计算
2. 可以通过 ndarray.ndim来查看数组的维度
3. 可以通过 ndarray.shape来查看数值的形状(⼏组⼏⾏⼏列)
4, 可以通过 reshape来修改数组的⼀个形状 不会影响原来的数组 ⽽是将修改后的结果返回给⼀
个新的对象
 注意: 修改后的元素个数必须和原来的个数⼀致 ⽐如原来是(2,6) 那么修改后可以是(3,
4) 但是不能这样写(1,4)
5. 可以通过 ndarray.size 来查看数组总共有多少元素
6. 可以