In [1]:
import numpy as np

In [2]:
a = np.random.randint(1,10,size=(3,4))
a

array([[7, 2, 8, 8],
       [8, 1, 6, 2],
       [9, 8, 3, 4]], dtype=int32)

In [3]:
b = a.reshape((2,6))
b

array([[7, 2, 8, 8, 8, 1],
       [6, 2, 9, 8, 3, 4]], dtype=int32)

In [4]:
a

array([[7, 2, 8, 8],
       [8, 1, 6, 2],
       [9, 8, 3, 4]], dtype=int32)

In [6]:
# resize 会直接修改数组本身
# reshape 不会修改数组本身，返回一个新的数组
a2 = np.arange(24).reshape(3,8)
print(a2)
a2.resize(4,6)
print(a2)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
