In [1]:
import numpy as np

In [4]:
# flatten 和 ravl多维转化为一维
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
a3 = arr.flatten()[1]-100 #flatten是将数组转换成⼀位数数组后，然后将这数组拷⻉回去，后续对这个数组进⾏修改不会影响之前的数组
a3

np.int64(-98)

In [8]:
c = np.arange(0,10).reshape((2,5))
c

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [14]:
c3 = c.ravel() # ravel:把引⽤地址返回回去,所有对其本数据进⾏修改会影响之前的数据
c3[1] = c3[1]+100
c3

array([  0, 101,   2,   3,   4,   5,   6,   7,   8,   9])

In [15]:
c

array([[  0, 101,   2,   3,   4],
       [  5,   6,   7,   8,   9]])

In [ ]:
# 1.flatten 和ravel都是改变数组形状的，但是flatten不会改变数组本身，而是返回一个新的数组，ravel会直接修改数组本身
"""
总结:1.reshape和resize都是重新定义形状的, 但是 reshape不会修改数组的本身,⽽是将修改后的结果返回回去给⼀个新的对象    resize 是直接修改数组本身
2. 02.flatten和ravel 都是⽤来将数组转变问⼀维数组,并且他们都不会对源数据造成修改,但是flatten返回的是⼀个拷⻉,所有对02.flatten和ravl.ipynb
的返回值的修改不会影响其他(原来)的数组,ravel返回的是⼀个引⽤地址,那么会对原来的值进⾏修改
""";