In [1]:
import numpy as np

In [3]:
# vstack 列相同,按照垂直方向的叠加
a1 = np.random.randint(1,10,size=(4,5))
print(a1)
a2 = np.random.randint(1,10,size=(1,5))
print(a2)
a3 = np.vstack([a1,a2])
a3

[[6 9 2 5 3]
 [2 3 3 1 2]
 [7 2 4 7 4]
 [1 2 9 8 7]]
[[1 1 4 9 3]]


array([[6, 9, 2, 5, 3],
       [2, 3, 3, 1, 2],
       [7, 2, 4, 7, 4],
       [1, 2, 9, 8, 7],
       [1, 1, 4, 9, 3]], dtype=int32)

In [11]:
# hstack :行相同，将数组按照水平方向叠加，数组的行必须相同才可以叠加
a1 = np.random.randint(1,10,size=(3,5))
print(a1)
a2 = np.random.randint(1,10,size=(3,1))
print(a2)
a3 = np.hstack([a1,a2])
a3

[[4 4 1 9 8]
 [1 8 5 7 3]
 [3 6 5 8 2]]
[[8]
 [3]
 [3]]


array([[4, 4, 1, 9, 8, 8],
       [1, 8, 5, 7, 3, 3],
       [3, 6, 5, 8, 2, 3]], dtype=int32)

In [10]:
# concatenate([a,b],axis=0/1/None)
f1 = np.array([[1,2],[3,4]]) # 二行二列
f2 = np.array([[5,6]]) # 一行二列
f3 = np.concatenate([f1,f2],axis=0) # axis的值 0,代表垂直叠加,列必须相同。1，代表水平叠加，行必须相同。None,代表先叠加，在转换为一维数组
# f3 = np.concatenate([f1,f2.T],axis=1)
# f3 = np.concatenate([f1,f2.T],axis=None)
f3

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
"""
1.np.hstack([a,b]),水平叠加，但前提是行相同。
2.np.vstack([a,b]),垂直叠加，但前提是列相同。
3.np.concatenate([a,b],axis=0/1/None),手动调整方向，axis为0，代表垂直叠加。为1，代表水平叠加。为None，代表先叠加，在转换为一维数组。
"""