In [1]:
import numpy as np

In [2]:
a = np.arange(0,24).reshape(4,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [3]:
a[2] = 0
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [ 0,  0,  0,  0,  0,  0],
       [18, 19, 20, 21, 22, 23]])

In [4]:
a2 = np.arange(24).reshape(4,6)
a2

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [5]:
a2[a2%2==0] = 0 # 通过条件来实现
a2

array([[ 0,  1,  0,  3,  0,  5],
       [ 0,  7,  0,  9,  0, 11],
       [ 0, 13,  0, 15,  0, 17],
       [ 0, 19,  0, 21,  0, 23]])

In [8]:
a3 = np.arange(24).reshape(4,6)
a3

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [9]:
a4 = np.where(a3<5,1,0)
a4

array([[1, 1, 1, 1, 1, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [10]:
a5 = np.arange(24).reshape(4,6)
a5[2,4] = 36
a5

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 36, 17],
       [18, 19, 20, 21, 22, 23]])

In [ ]:
'''
总结:
1. 可以使⽤所有或者切⽚来替换
2. 使⽤条件替换
3. 使⽤where来进⾏替换
'''