In [1]:
import numpy as np

In [2]:
# 1.将np,arange(10)数组中的奇数全部都替换成-1.
a = np.arange(10)
a[a%2==1] = -1
a

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [62]:
#  2.有⼀个4⾏4列的数组（⽐如：np.random.randint(0,10,size=(4,4)),请将其中对⻆线的数取出来形成⼀个⼀维数组，提示(使⽤np.eye)·
b = np.random.randint(0,10,size=(4,4))
print(b)
mask_eye = np.eye(4,dtype=bool)
print(mask_eye)
b[mask_eye]

[[0 1 2 4]
 [8 1 9 4]
 [7 8 4 8]
 [7 3 5 7]]
[[ True False False False]
 [False  True False False]
 [False False  True False]
 [False False False  True]]


array([0, 1, 4, 7], dtype=int32)

In [ ]:
 # 3.有⼀个4⾏4列的数组，请取出其中(0,0),(1,2),(3,2)的点。
c = np.arange(16).reshape(4,4)
print(c[0,0])
print(c[1,2])
print(c[3,2])

In [22]:
# 4.有⼀个4⾏4列的数组，请取出其中2:3⾏(包括第3⾏)的所有数据。
d = np.random.randint(1,5,size=(4,4))
print(d)
print(d[2:4])

[[1 3 2 1]
 [2 2 3 1]
 [4 4 1 2]
 [1 1 3 4]]
[[4 4 1 2]
 [1 1 3 4]]


In [64]:
# 5.有⼀个8⾏9列的数组，请将其中1-6⾏(包含第5⾏)的第8列⼤于3的数全部都取出来。 
e = np.arange(72).reshape((8,9))
print(e)
print(e[1:6, 8][e[1:6, 8] > 3])
# e[1:6,8] 得到一个一维数组
print(e[1:6,8]>3)

[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]
 [27 28 29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42 43 44]
 [45 46 47 48 49 50 51 52 53]
 [54 55 56 57 58 59 60 61 62]
 [63 64 65 66 67 68 69 70 71]]
[17 26 35 44 53]
[ True  True  True  True  True]


In [40]:
# 6.替换数组中所有⼩于平均值的元素
arr = np.random.randint(0,25,size=(5,5))
mean_value = arr.mean()
print(arr)
print(mean_value)
arr[arr<mean_value] = mean_value
print(arr)

[[18 23  7 24 10]
 [ 7  8 16 21 18]
 [10  2 23  8 24]
 [23  0 19 23 23]
 [12 19 14  3  9]]
14.56
[[18 23 14 24 14]
 [14 14 16 21 18]
 [14 14 23 14 24]
 [23 14 19 23 23]
 [14 19 14 14 14]]


In [41]:
# 7.将⼀个数组的边框元素设置为0
y = np.arange(24).reshape(4,6)
y[0]= 0 # 将第一行设置为0
y[-1] = 0 # 将最后一行设置为0
y[:,0] = 0 # 将第一列设置为0
y[:,-1] = 0 # 将最后一列设置为0
y

array([[ 0,  0,  0,  0,  0,  0],
       [ 0,  7,  8,  9, 10,  0],
       [ 0, 13, 14, 15, 16,  0],
       [ 0,  0,  0,  0,  0,  0]])

In [52]:
#  8.反转⼆维数组的⾏
u = np.arange(16).reshape(4,4)
print(u)
i = u[::-1]
print(i)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[12 13 14 15]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


In [59]:
# 9. 将3D数组的最后⼀个维度进⾏求和
arr2 = np.random.randint(1,5,size=(3,2,4))
print(arr2)
sum = arr2.sum(axis=-1)[2].sum() # arr2.sum(axis=-1)可以理解为变成了二维数组
print(sum)

[[[2 4 4 2]
  [3 4 1 4]]

 [[2 3 3 2]
  [4 1 4 4]]

 [[2 1 2 4]
  [2 3 3 3]]]
20


In [61]:
# 10.选择数组中的⾮对⻆线元素
arr3 = np.arange(25).reshape(5,5)
print(arr3)
eye_mask02 = np.eye(5,dtype=bool)
print(eye_mask02)
print(arr3[~eye_mask02])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ True False False False False]
 [False  True False False False]
 [False False  True False False]
 [False False False  True False]
 [False False False False  True]]
[ 1  2  3  4  5  7  8  9 10 11 13 14 15 16 17 19 20 21 22 23]
