In [1]:
import numpy as np

In [3]:
# 1. shape为(3,8,2)的数组能和(8,3)的数组进⾏运算吗？
a = np.random.randint(0,5,size=(3,8,2))
# b = np.random.randint(0,5,size=(8,3))
b = np.random.randint(0,5,size=(8,2))
c = a + b
c

array([[[2, 6],
        [6, 4],
        [4, 2],
        [6, 4],
        [5, 6],
        [4, 4],
        [1, 1],
        [1, 3]],

       [[5, 6],
        [4, 5],
        [1, 6],
        [3, 0],
        [7, 6],
        [2, 2],
        [4, 2],
        [1, 6]],

       [[4, 6],
        [7, 5],
        [1, 2],
        [4, 0],
        [6, 5],
        [4, 2],
        [4, 3],
        [2, 6]]], dtype=int32)

In [5]:
# 2. shape为(3,8,2)：的数组能和(8,1)的数组进⾏运算吗？
a = np.random.randint(0,5,size=(3,8,2))
print(a)
# b = np.random.randint(0,5,size=(8,3))
b = np.random.randint(0,5,size=(8,1))
print(b)
c = a + b # 如果在任何维度上⼤⼩不⼀致两个数组⼦啊该维度上的⼤⼩都不为1
c

[[[3 3]
  [2 3]
  [4 2]
  [1 1]
  [3 4]
  [3 0]
  [4 1]
  [1 2]]

 [[2 0]
  [2 4]
  [2 1]
  [3 1]
  [2 4]
  [4 0]
  [4 0]
  [2 2]]

 [[2 2]
  [3 1]
  [0 4]
  [3 1]
  [4 2]
  [2 4]
  [3 3]
  [4 2]]]
[[1]
 [1]
 [4]
 [2]
 [4]
 [2]
 [2]
 [3]]


array([[[4, 4],
        [3, 4],
        [8, 6],
        [3, 3],
        [7, 8],
        [5, 2],
        [6, 3],
        [4, 5]],

       [[3, 1],
        [3, 5],
        [6, 5],
        [5, 3],
        [6, 8],
        [6, 2],
        [6, 2],
        [5, 5]],

       [[3, 3],
        [4, 2],
        [4, 8],
        [5, 3],
        [8, 6],
        [4, 6],
        [5, 5],
        [7, 5]]], dtype=int32)

In [6]:
# 3. shape为(3,1,8)的数组能和(8,1)的数组进⾏运算吗？
a = np.random.randint(0,5,size=(3,1,8))
# b = np.random.randint(0,5,size=(8,3))
b = np.random.randint(0,5,size=(8,1))
c = a + b
c

array([[[8, 4, 7, 4, 4, 8, 5, 7],
        [8, 4, 7, 4, 4, 8, 5, 7],
        [8, 4, 7, 4, 4, 8, 5, 7],
        [4, 0, 3, 0, 0, 4, 1, 3],
        [7, 3, 6, 3, 3, 7, 4, 6],
        [7, 3, 6, 3, 3, 7, 4, 6],
        [6, 2, 5, 2, 2, 6, 3, 5],
        [7, 3, 6, 3, 3, 7, 4, 6]],

       [[5, 8, 5, 4, 7, 8, 6, 8],
        [5, 8, 5, 4, 7, 8, 6, 8],
        [5, 8, 5, 4, 7, 8, 6, 8],
        [1, 4, 1, 0, 3, 4, 2, 4],
        [4, 7, 4, 3, 6, 7, 5, 7],
        [4, 7, 4, 3, 6, 7, 5, 7],
        [3, 6, 3, 2, 5, 6, 4, 6],
        [4, 7, 4, 3, 6, 7, 5, 7]],

       [[8, 5, 7, 5, 7, 7, 8, 6],
        [8, 5, 7, 5, 7, 7, 8, 6],
        [8, 5, 7, 5, 7, 7, 8, 6],
        [4, 1, 3, 1, 3, 3, 4, 2],
        [7, 4, 6, 4, 6, 6, 7, 5],
        [7, 4, 6, 4, 6, 6, 7, 5],
        [6, 3, 5, 3, 5, 5, 6, 4],
        [7, 4, 6, 4, 6, 6, 7, 5]]], dtype=int32)

In [ ]:
# 1.数组和数字之间直接进行运算是没有任何问题的
# 2.相同shape数组之间可以进行运算
# 3.如果两个shape不相同的数字想要进行运算那么就需要看他们是否满足了广播机制
# 4.如果两个数组的后缘维度即从末尾开始算起维度M轴长度相符合或者其中一方的长度为1，他们是广播兼容的
# 广播会在缺失（或者）长度为1的维度上进行