In [1]:
import numpy as np

In [3]:
a = [1,2,3,4,5,6]
b = []
for i in a:
    b.append(i+1)
a = b
a

[2, 3, 4, 5, 6, 7]

In [5]:
a = np.random.random((3,4))
a

array([[0.61880463, 0.76608948, 0.66565595, 0.2537833 ],
       [0.61735548, 0.84604695, 0.63764839, 0.74306881],
       [0.9858032 , 0.26157241, 0.49494642, 0.66960142]])

In [6]:
b = a*10
b

array([[6.18804629, 7.6608948 , 6.65655951, 2.53783305],
       [6.17355476, 8.46046946, 6.37648394, 7.43068813],
       [9.85803203, 2.61572407, 4.94946421, 6.69601415]])

In [7]:
c = a+1
c

array([[1.61880463, 1.76608948, 1.66565595, 1.2537833 ],
       [1.61735548, 1.84604695, 1.63764839, 1.74306881],
       [1.9858032 , 1.26157241, 1.49494642, 1.66960142]])