In [ ]:
import numpy as np
a1 = [1,2,3,'4']
print(a1)
# http://localhost:8888/tree?token=b2a4e1f0b11b911904c8a43c508d6896561c04893da68b61
b1 = np.array([[1,2,3,'4'],[5,6,7,8]])
print(b1)
type(b1)

In [2]:
a4 = np.arange(1,50,1)
print(a4)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49]


In [6]:
a5 = np.random.random((3,4))
print(a5)
a6 = np.random.randint(0,50,size=(5,10))
print(a6)

[[0.54787567 0.43294983 0.77586793 0.33046994]
 [0.36152614 0.74272817 0.87964811 0.86693618]
 [0.14039011 0.18614891 0.04971628 0.79289756]]
[[20 33 48 22 16 37 45 46 35 17]
 [14 42  0  2 25 25  3 30 12 18]
 [38 10 48 22 19 49 10 39 12 18]
 [37 47 28 45 33 48 17 11 35 19]
 [25 11 49 23 20 35 44 40 18 17]]


In [7]:
a7 = np.zeros((2,2)) # 生成一个都为0的2行2列的数组
a8 = np.ones((2,2)) # 生成一个都为1的2行2列的数组
print(a7)
print(a8)

[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]


In [8]:
a9 = np.full((3,4),2) # 生成一个都为x的3行4列的数组，x = 2
a9

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [9]:
a10 = np.eye(3) # 生产一个在对角线元素都为1，其他都为0的3*3矩阵
a10

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])